FROM node:14 AS builder

RUN git clone https://github.com/bezkoder/react-crud-web-api.git /frontend
WORKDIR /frontend
RUN npm install
COPY http-common.js /frontend/src

RUN npm run-script build

FROM nginx
COPY --from=builder /frontend/build  /usr/share/nginx/html
COPY default.conf.template /etc/nginx/templates/   
EXPOSE 80