apiVersion: v1
kind: Pod
metadata:
  name: tutorialsappbackend
  labels:
    app: backend
spec:
  containers:
  - image: backend
    imagePullPolicy: Never
    name: backend
    ports:
      - containerPort: 8080
    env:
    - name: DB_HOST
      value: database 
    - name: DB_USER
      value: "tutorials"
    - name: DB_PASSWORD
      value: "password" 
    - name: MYSQL_DB
      value: "tutorials"
  restartPolicy: OnFailure     