apiVersion: v1
kind: Pod
metadata:
  name: tutorialsapp
  labels:
    app: demo.33
spec:
  containers:
  - image: frontend
    imagePullPolicy: Never
    name: frontend
    ports:
      - containerPort: 80
    env:
    - name: API_PROXY_PASS
      value: http://backend:8080 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo.33
  type: NodePort 

---
apiVersion: v1
kind: Pod
metadata:
  name: tutorialsdatabase
  labels:
    app: database
spec:
  containers:
  - image: mysql
    imagePullPolicy: Never
    name: database
    ports:
      - containerPort: 3306

---  
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  # type:   
  ports:
  - name: http
    protocol: TCP
    port: 3306
    targetPort: 3306
---          
apiVersion: v1
kind: Pod
metadata:
  name: tutorialsappbackend
  labels:
    app: backend
spec:
  containers:
  - image: backend
    imagePullPolicy: Never
    name: backend
    ports:
      - containerPort: 8080
    env:
    - name: DB_HOST
      value: database 
    - name: DB_USER
      value: "tutorials"
    - name: DB_PASSWORD
      value: "password" 
    - name: MYSQL_DB
      value: "tutorials"
  restartPolicy: OnFailure             
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    

